import { PlanetData } from './store';

// 1 AU (Earth Distance) = 50 units in Real Scale Mode
// Earth Radius (1 unit) = 1 unit in Real Scale Mode (Sun is 109 units!)

export const planetData: (PlanetData & { distanceAU: number; relativeRadius: number })[] = [
    {
        name: 'Mercury',
        radius: 0.4,
        distance: 20,
        speed: 0.5,
        texture: '/textures/mercury.jpg',
        yearDuration: '88 Earth Days',
        dayDuration: '59 Earth Days',
        temperature: '167°C',
        moons: 0,
        realDistance: '57.9 million km',
        description: "The smallest planet in the Solar System and the closest to the Sun. It has a rocky body like Earth.",
        funFact: "Mercury shrinks as it cools, having lost 7km in radius over 4 billion years.",
        distanceAU: 0.39,
        relativeRadius: 0.38
    },
    {
        name: 'Venus',
        radius: 0.9,
        distance: 25,
        speed: 0.35,
        texture: '/textures/venus.jpg',
        yearDuration: '225 Earth Days',
        dayDuration: '243 Earth Days',
        temperature: '464°C',
        moons: 0,
        realDistance: '108.2 million km',
        description: "Spinning in the opposite direction to most planets, Venus is the hottest planet in our solar system.",
        funFact: "A day on Venus is longer than a year on Venus!",
        distanceAU: 0.72,
        relativeRadius: 0.95
    },
    {
        name: 'Earth',
        radius: 1.0,
        distance: 32,
        speed: 0.25,
        texture: '/textures/earth.jpg',
        yearDuration: '365.25 Days',
        dayDuration: '24 Hours',
        temperature: '15°C',
        moons: 1,
        realDistance: '149.6 million km',
        description: "Our home planet, the only place we know of so far that's inhabited by living things.",
        funFact: "Earth's atmosphere protects us from meteoroids, most break up before hitting the surface.",
        distanceAU: 1.0,
        relativeRadius: 1.0
    },
    {
        name: 'Mars',
        radius: 0.5,
        distance: 40,
        speed: 0.2,
        texture: '/textures/mars.jpg',
        yearDuration: '687 Earth Days',
        dayDuration: '24h 37m',
        temperature: '-65°C',
        moons: 2,
        realDistance: '227.9 million km',
        description: "A dusty, cold, desert world with a very thin atmosphere. Evidence suggests Mars was once wetter and warmer.",
        funFact: "Mars is home to Olympus Mons, the tallest volcano in the solar system.",
        distanceAU: 1.52,
        relativeRadius: 0.53
    },
    {
        name: 'Jupiter',
        radius: 5.0,
        distance: 90,
        speed: 0.1,
        texture: '/textures/jupiter.jpg',
        yearDuration: '12 Earth Years',
        dayDuration: '9h 56m',
        temperature: '-110°C',
        moons: 79,
        realDistance: '778.5 million km',
        description: "The largest planet in the Solar System, a gas giant with a Great Red Spot storm larger than Earth.",
        funFact: "Jupiter's Great Red Spot is a storm that has been raging for hundreds of years.",
        distanceAU: 5.2,
        relativeRadius: 11.2
    },
    {
        name: 'Saturn',
        radius: 4.5,
        distance: 120,
        speed: 0.07,
        texture: '/textures/saturn.jpg',
        hasRing: true,
        ringTexture: '/textures/saturn-ring.png',
        yearDuration: '29 Earth Years',
        dayDuration: '10h 42m',
        temperature: '-140°C',
        moons: 82,
        realDistance: '1.4 billion km',
        description: "Adorned with a dazzling, complex system of icy rings, Saturn is unique in our solar system.",
        funFact: "Saturn is the only planet in our solar system that is less dense than water.",
        distanceAU: 9.58,
        relativeRadius: 9.45
    },
    {
        name: 'Uranus',
        radius: 3.0,
        distance: 150,
        speed: 0.05,
        texture: '/textures/uranus.jpg',
        yearDuration: '84 Earth Years',
        dayDuration: '17h 14m',
        temperature: '-195°C',
        moons: 27,
        realDistance: '2.9 billion km',
        description: "The seventh planet from the Sun, and has the third-largest diameter. It rotates on its side.",
        funFact: "Uranus rotates at a nearly 90-degree angle from the plane of its orbit.",
        distanceAU: 19.2,
        relativeRadius: 4.0
    },
    {
        name: 'Neptune',
        radius: 3.0,
        distance: 180,
        speed: 0.03,
        texture: '/textures/neptune.jpg',
        yearDuration: '165 Earth Years',
        dayDuration: '16h 6m',
        temperature: '-200°C',
        moons: 14,
        realDistance: '4.5 billion km',
        description: "Dark, cold, and whipped by supersonic winds, ice giant Neptune is the eighth and most distant planet.",
        funFact: "Neptune was the first planet located through mathematical calculations.",
        distanceAU: 30.05,
        relativeRadius: 3.88
    },
];
