import { PlanetData } from './store';

// 1 AU (Earth Distance) = 50 units in Real Scale Mode
// Earth Radius (1 unit) = 1 unit in Real Scale Mode (Sun is 109 units!)

export const planetData: PlanetData[] = [
    {
        name: 'Sun',
        radius: 16, // Matches the Sun component size
        distance: 0,
        speed: 0,
        color: '#FFCC00',
        texture: '/textures/sun.jpg',
        description: "The Sun is the star at the center of the Solar System. It is a nearly perfect sphere of hot plasma, heated to incandescence by nuclear fusion reactions in its core.",
        yearDuration: '230 million years (Galactic)',
        dayDuration: '27 Earth Days',
        temperature: '5,500°C (Surface)',
        moons: 0,
        realDistance: '0 km',
        funFact: "The Sun accounts for 99.86% of the mass in the solar system.",
        distanceAU: 0,
        relativeRadius: 109,
        type: 'Star',
        gravity: '274 m/s²',
        surfaceArea: '6.09 × 10¹² km²',
        composition: 'Hydrogen (73%), Helium (25%)',
        notableMoons: [],
        artificialSatellites: [
            { name: 'Parker Solar Probe', type: 'Probe' },
            { name: 'SOHO', type: 'Observatory' }
        ]
    },
    {
        name: 'Mercury',
        radius: 0.4,
        distance: 20,
        speed: 0.01,
        color: '#A5A5A5',
        texture: '/textures/mercury.jpg',
        description: "The smallest planet in our solar system and closest to the Sun—is only slightly larger than Earth's Moon. Mercury is the fastest planet, zipping around the Sun every 88 Earth days.",
        yearDuration: '88 Earth Days',
        dayDuration: '59 Earth Days',
        temperature: '167°C',
        moons: 0,
        realDistance: '57.9 million km',
        funFact: "Mercury shrinks as it cools, having lost 7km in radius over 4 billion years.",
        distanceAU: 0.39,
        relativeRadius: 0.38,
        type: 'Planet',
        gravity: '3.7 m/s²',
        surfaceArea: '7.48 × 10⁷ km²',
        composition: 'Rocky (Silicate surface, Iron core)',
        notableMoons: [],
        artificialSatellites: [
            { name: 'MESSENGER', type: 'Orbiter' },
            { name: 'BepiColombo', type: 'Mission' }
        ]
    },
    {
        name: 'Venus',
        radius: 0.9,
        distance: 25,
        speed: 0.007,
        color: '#E3BB76',
        texture: '/textures/venus.jpg',
        description: "Spinning in the opposite direction to most planets, Venus is the hottest planet in our solar system with a thick atmosphere that traps heat in a runaway greenhouse effect.",
        yearDuration: '225 Earth Days',
        dayDuration: '243 Earth Days',
        temperature: '464°C',
        moons: 0,
        realDistance: '108.2 million km',
        funFact: "A day on Venus is longer than a year on Venus!",
        distanceAU: 0.72,
        relativeRadius: 0.95,
        type: 'Planet',
        gravity: '8.87 m/s²',
        surfaceArea: '4.60 × 10⁸ km²',
        composition: 'Rocky (Silicate crust, Iron core)',
        notableMoons: [],
        artificialSatellites: [
            { name: 'Akatsuki', type: 'Orbiter' },
            { name: 'Magellan', type: 'Mapper' }
        ]
    },
    {
        name: 'Earth',
        radius: 1,
        distance: 32,
        speed: 0.005,
        color: '#2233FF',
        texture: '/textures/earth.jpg',
        description: "Our home planet is the third planet from the Sun, and the only place we know of so far that's inhabited by living things. It's the only world in our solar system with liquid water on the surface.",
        yearDuration: '365.25 Days',
        dayDuration: '24 Hours',
        temperature: '15°C',
        moons: 1,
        realDistance: '149.6 million km',
        funFact: "Earth is the only planet not named after a god.",
        distanceAU: 1.00,
        relativeRadius: 1.00,
        type: 'Planet',
        gravity: '9.8 m/s²',
        surfaceArea: '5.10 × 10⁸ km²',
        composition: 'Rocky (Nitrogen-Oxygen Atmosphere)',
        notableMoons: ['The Moon'],
        artificialSatellites: [
            { name: 'ISS', type: 'Space Station' },
            { name: 'Hubble', type: 'Telescope' },
            { name: 'Tiangong', type: 'Space Station' }
        ]
    },
    {
        name: 'Mars',
        radius: 0.5,
        distance: 40,
        speed: 0.004,
        color: '#E27B58',
        texture: '/textures/mars.jpg',
        description: "Mars is a dusty, cold, desert world with a very thin atmosphere. There is strong evidence that Mars was—billions of years ago—wetter and warmer, with a thicker atmosphere.",
        yearDuration: '687 Earth Days',
        dayDuration: '24h 37m',
        temperature: '-65°C',
        moons: 2,
        realDistance: '227.9 million km',
        funFact: "Mars is home to Olympus Mons, the tallest volcano in the solar system.",
        distanceAU: 1.52,
        relativeRadius: 0.53,
        type: 'Planet',
        gravity: '3.71 m/s²',
        surfaceArea: '1.44 × 10⁸ km²',
        composition: 'Rocky (Iron Oxide dust)',
        notableMoons: ['Phobos', 'Deimos'],
        artificialSatellites: [
            { name: 'Perseverance', type: 'Rover' },
            { name: 'Curiosity', type: 'Rover' },
            { name: 'Ingenuity', type: 'Helicopter' }
        ]
    },
    {
        name: 'Jupiter',
        radius: 2.5,
        distance: 90,
        speed: 0.002,
        color: '#C88B3A',
        texture: '/textures/jupiter.jpg',
        description: "Jupiter has a long history of surprising scientists—all the way back to 1610 when Galileo Galilei found the first moons beyond Earth. It is the largest planet in the solar system.",
        yearDuration: '12 Earth Years',
        dayDuration: '9h 56m',
        temperature: '-110°C',
        moons: 79,
        realDistance: '778.6 million km',
        funFact: "Jupiter's Great Red Spot is a storm that has been raging for at least 400 years.",
        distanceAU: 5.20,
        relativeRadius: 11.21,
        type: 'Planet',
        gravity: '24.79 m/s²',
        surfaceArea: '6.14 × 10¹⁰ km²',
        composition: 'Gas Giant (Hydrogen, Helium)',
        notableMoons: ['Ganymede', 'Callisto', 'Io', 'Europa'],
        artificialSatellites: [
            { name: 'Juno', type: 'Orbiter' },
            { name: 'Galileo', type: 'Probe' }
        ]
    },
    {
        name: 'Saturn',
        radius: 2.2,
        distance: 120,
        speed: 0.0015,
        color: '#E3E0C0',
        texture: '/textures/saturn.jpg',
        hasRing: true,
        ringTexture: '/textures/saturn-ring.png',
        description: "Adorned with a dazzling, complex system of icy rings, Saturn is unique in our solar system. The other giant planets have rings, but none are as spectacular as Saturn's.",
        yearDuration: '29 Earth Years',
        dayDuration: '10h 42m',
        temperature: '-140°C',
        moons: 82,
        realDistance: '1.4 billion km',
        funFact: "Saturn is the only planet in our solar system that is less dense than water.",
        distanceAU: 9.58,
        relativeRadius: 9.45,
        type: 'Planet',
        gravity: '10.44 m/s²',
        surfaceArea: '4.27 × 10¹⁰ km²',
        composition: 'Gas Giant (Hydrogen, Helium)',
        notableMoons: ['Titan', 'Enceladus', 'Mimas', 'Rhea'],
        artificialSatellites: [
            { name: 'Cassini', type: 'Orbiter' },
            { name: 'Huygens', type: 'Lander' }
        ]
    },
    {
        name: 'Uranus',
        radius: 1.5,
        distance: 150,
        speed: 0.001,
        color: '#A6D9F0',
        texture: '/textures/uranus.jpg',
        description: "Uranus spins on its side. It is an ice giant, composed mostly of flowing icy materials above a solid core. It has a faint ring system and 27 known moons.",
        yearDuration: '84 Earth Years',
        dayDuration: '17h 14m',
        temperature: '-195°C',
        moons: 27,
        realDistance: '2.9 billion km',
        funFact: "Uranus rotates on its side, rolling around the Sun like a ball.",
        distanceAU: 19.22,
        relativeRadius: 4.01,
        type: 'Planet',
        gravity: '8.69 m/s²',
        surfaceArea: '8.08 × 10⁹ km²',
        composition: 'Ice Giant (Water, Methane, Ammonia)',
        notableMoons: ['Titania', 'Oberon', 'Umbriel', 'Ariel'],
        artificialSatellites: [
            { name: 'Voyager 2', type: 'Flyby' }
        ]
    },
    {
        name: 'Neptune',
        radius: 1.5,
        distance: 180,
        speed: 0.0008,
        color: '#3E54E8',
        texture: '/textures/neptune.jpg',
        description: "Dark, cold, and whipped by supersonic winds, ice giant Neptune is the eighth and most distant planet in our solar system. It is the only planet found by mathematical prediction.",
        yearDuration: '165 Earth Years',
        dayDuration: '16h 6m',
        temperature: '-201°C',
        moons: 14,
        realDistance: '4.5 billion km',
        funFact: "Neptune has the strongest winds in the solar system, reaching 1,200 miles per hour.",
        distanceAU: 30.05,
        relativeRadius: 3.88,
        type: 'Planet',
        gravity: '11.15 m/s²',
        surfaceArea: '7.61 × 10⁹ km²',
        composition: 'Ice Giant (Water, Methane, Ammonia)',
        notableMoons: ['Triton', 'Proteus', 'Nereid'],
        artificialSatellites: [
            { name: 'Voyager 2', type: 'Flyby' }
        ]
    }
];
